### ISSUE TITLE
Adding ending slash to url

### ISSUE THREAD

**Issue by ebisbe** [codemix/yii2-localeurls#44]
Hello,
I'm using your extension and for Seo reasons I need to have some urls ending with slash. Navigating through forums and yii2 references I found that the way to do that is by adding the slash as a suffix

```
['pattern' => '<nombreGoogle>-tickets', 'route' => 'site/parser', 'suffix' => '/'],
```
But once I want to define a folder language in order to create a url like /es/barcelona-tickets/ the ending slash is trimmed.
I've found that removing 
```
$url = rtrim($url, '/');
```
from the UrlManager.php file solves that. Is there any reason for having the rtrim ??

**Comment by mikehaertl** [comment]
Had not much time to look closer. From a quick test the unit tests now fail. Basically some home URLs would then also have a trailing slash, which does not look nice. But probably it wouldn't really matter. The only thing is that it would be a minor break in backward compatibility. I want to avoid that whenever possible. Need to think about a proper fix.

```
1) UrlManagerTest::testCreateHomeUrlWithLanguageFromUrl
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/de'
+'/de/'

/home/mike/projects/yii2-localeurls/tests/UrlManagerTest.php:425
/usr/bin/phpunit:537

2) UrlManagerWithBaseUrlTest::testCreateHomeUrlWithLanguageFromUrl
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/base/de'
+'/base/de/'

/home/mike/projects/yii2-localeurls/tests/UrlManagerTest.php:425
/usr/bin/phpunit:537

3) UrlManagerWithScriptNameAndBaseUrlTest::testCreateHomeUrlWithLanguageFromUrl
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/base/index.php/de'
+'/base/index.php/de/'

/home/mike/projects/yii2-localeurls/tests/UrlManagerTest.php:425
/usr/bin/phpunit:537

4) UrlManagerWithScriptNameTest::testCreateHomeUrlWithLanguageFromUrl
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/index.php/de'
+'/index.php/de/'
```

**Comment by mikehaertl** [comment]
Any fix should also consider the discussion in #39.

**Comment by ebisbe** [comment]
I've been reviewing the tests that fail and understanding why is coded like that. From what I see the line I wanted to delete ( UrlManager.php:201 )  is just a work arround for being able to define a home route without the trailing slash with the added language. The problem is that you could really need that trailing slash for Seo reasons and the code is deleting it without asking. 
If you update the rule to something like:
```
'rules' => [
                'home' => 'site/index',
            ],
```
the resulting test is /de/home , without the ending trailing slash. So the problem itself is with the definition of an empty key rule because yii2 is not adding the ending trailing slash unless you especify that in the rule with something like:
```
['pattern' => '<nombreGoogle>-tickets', 'route' => 'site/parser', 'suffix' => '/'],
```
An empty key rule will always return / from yii2 because yii2 doesn't know that you will add /de or whatever. 

The only clean solution I've found is to only rtrim the urls that their pattern is empty and their suffix is different from '/'.

I'll make a PR with the example and another test to have both options for the home route.

**Comment by mikehaertl** [comment]
As mentioned in the PR: I need more time first to rethink the situation. As this is the second time, that someone mentions trailing slashes in the context of SEO: Could you explain, why that is a problem? Or point me to some documentation about the problem?

**Comment by ebisbe** [comment]
Yes I can explain. The problem is about duplicated content. Bots that crawl all the webs interpret the ending trailing slash as diferent urls. 
For example http://www.site.com/de and http://www.site.com/de/ will be duplicated content. From a Seo perspective you can do differents things to solve it. 
The easiest way but not the cleaner is add a rel="canonical" or you can choose to redirect all ending urls with a trailing slash to not ending with trailing slash or viceversa. It really doesn't matter which option you choose. But with the code like it's now code you can't choose.

You can read further information at: http://googlewebmastercentral.blogspot.com.es/2010/04/to-slash-or-not-to-slash.html
I just googled: **google duplicated content trailing slash**

**Comment by mikehaertl** [comment]
Ok, so far so good. But that does not explain, why you need the trailing slash. By default, there is no trailing slash, so no duplicate content, because all URLs are without trailing slash by default. So why do you need URLs that *have* a trailing slash?

**Comment by ebisbe** [comment]
Because as I said is an option to have them or not and our Seo Manager wants all urls with the trailing slash. We have them all like that in our other framework. We are migrating to yii2 and we need to maintain them as they are now.

**Comment by mikehaertl** [comment]
How about another config option `public $trailingSlash = false;`? I first thought about `$suffix` - but I don't want to add features here, that not even the core framework provides and that are not related to the main task of the extension. If someone needs a different suffix, they can then still use URL rules.

**Comment by mikehaertl** [comment]
I've done a quick implementation. Can you check, if this solves your problem?

**Comment by mikehaertl** [comment]
@ebisbe Any updates here? Would be great to get some feedback on that new option.

**Comment by OndrejVasicek** [comment]
Hi,
until yesterday I used version 1.0.6 and everything was fine. Today I updated to the newest version, to try solve different problem, but get stuck on the same problem ebisbe wrote. 
From my point of view, you should really respect the original Yii2 setting “suffix”. If I set suffix to “/”, you shouldn’t delete it. So I don’t see any reason to add another trailingSlash property, if we already have more general property “suffix”.
Does it make any sense?  Maybe I got it wrong. (Sorry for my English)

**Comment by mikehaertl** [comment]
Unfortunately this is not so easy and bloats the class. So the `trailingSlash` would be a workaround. Why does it not work for you? 

Actually I also consider the solution to use `suffix` a pretty dirty hack. It's not really what `suffix` was introduced for (namely to add something like `.html` to all your pages).

**Comment by mikehaertl** [comment]
@OndrejVasicek Thanks for your suggestion. I've remove the `trailingSlash` option again and implemented your fix. The test cases still all succeed. So maybe you can help testing?

**Comment by OndrejVasicek** [comment]
You're welcome. I'd like to help you, but I have zero experience with being a part of “something” on github. Could you just lead me a bit? Should I just change my version in composer from "codemix/yii2-localeurls": "1.2.*", to something like "codemix/yii2-localeurls": "@master" and just manually try my system with your changes?

**Comment by mikehaertl** [comment]
From the top of my head: `"codemix/yii2-localeurls": "@dev"` should do it. It's a bit hard to find this information in the composer documentation. If it doesn't work, you may also wait some minutes as composer caches previous results for some time.

**Comment by OndrejVasicek** [comment]
Ok, this is strange as hell. The url's on the web seems to be ok. It's not a big web but there is a few different types of url. What is weird is, that the yii toolbar doesn’t work anymore. I delete the content of runtime and assets folder, restart apache, but still getting this message 
> Not Found (#404): Unable to find debug data tagged with '55f6a1b7bf384/'.

When I switch back to previous version, everything is ok. Bloody mystery. Trying to google it.

**Comment by mikehaertl** [comment]
Wait a second. It could be in line 375 - maybe we need to look at the suffix there too. I can have a look later. Maybe you want to investigate meanwhile.

**Comment by OndrejVasicek** [comment]
I can't see anything on 375, just "*" - part of comment. Do you mean the method redirectToLanguage()?

**Comment by mikehaertl** [comment]
I mean this:

```
    protected function redirectToLanguage($language)
    {
        $result = parent::parseRequest($this->_request);
        if ($result === false) {
            throw new \yii\web\NotFoundHttpException(Yii::t('yii', 'Page not found.'));
        }
```

**Comment by mikehaertl** [comment]
This trailing slash is really a nuisance. Yii's debug logging seems to tag requests by URL and somehow seems to have a problem with trailing slashes. Couldn't you simply turn off that trailing slash sufix during development? I know, it's not perfect, but at least you get your debug toolbar back.

**Comment by mikehaertl** [comment]
I've tried to improve the fix. It first appended a trailing slash even after some query params. That's not what we want. The change now only removes trailing slashes if `suffix!=='/'`.

Can you try again?

**Comment by OndrejVasicek** [comment]
I was digging into it the whole time, but you were still one step ahead :) Yes, it seems it works. You were right, the previous solutions wasn’t good. I can see it now.
Thank you a lot. Now, I can finally focus on the former problem, which I hope won’t create another issue.

**Comment by mikehaertl** [comment]
Ok, I've done some more minor improvements to also make this works for URLs with query params. There's a new `1.2.6` release with all the changes now.

Thanks all for helping to improve this little extension.

@ebisbe I'm closing this for now. If you still find issues, feel free to reopen.

**Comment by smilemd** [comment]
Hi guys,

after latest update to 1.2.6, this app doesn't work correctly because it add a suffix - "/" even if all urls are without it.

so at the moment, if we open for example:

http://site.loc/en -------------------------> http://site.loc/en/
http://site.loc/en/site/index   ---------->  http://site.loc/en/site/index/

it's not correct for seo and maybe someone want to use http://site.loc/en instead of http://site.loc/en/.

in my case, i use yii2 advanced template for my projects and configurated it that suffix for all urls is "/".

common/config/main.php

return [
    'components' =>
        [
            'request' => [
                'enableCsrfValidation' => true,
                'enableCookieValidation' => true,
            ],
            'urlManager' => [
                'enablePrettyUrl' => true,
                'enableStrictParsing' => false,
                'showScriptName' => false,
                'suffix' => '/',
            ],
        ]
];

after latest update to 1.2.6,  if i try to open:

http://site.loc  ---------------------->  http://site.loc/en//

**Comment by mikehaertl** [comment]
I don't understand: You say, you configured a suffix of `/`. So of course all your URLs will have a `/` at the end. If you don't want that, then why do you configure the suffix at all?

**Comment by mikehaertl** [comment]
Ok, I can reproduce the issue now and added test cases for them. I'll take a look soon.

**Comment by smilemd** [comment]
mikehaertl, you understand me partial correctly. I want to use urls with suffix of / .

But the problem is that after this update ( 1.2.6 ), if i try to open my app by name: http://site.com i'll be redirected to default or last stored language in cookes with double suffix at the end.

http://site.com ---> http://site.com/en//

**Comment by mikehaertl** [comment]
@smilemd Fix pushed. Can you help testing?

**Comment by smilemd** [comment]
i can take a look, but in tests i have zero experience :(

**Comment by mikehaertl** [comment]
You just have to test the code, not the test. If you don't know how to use latest master code, then simply change the sam lines as in this commit:

https://github.com/codemix/yii2-localeurls/commit/85cd638b23089c3637826d66fcd106dbcd5ebae7

**Comment by mikehaertl** [comment]
With "test" I mean: Check if that fixes the problem in your application.

**Comment by smilemd** [comment]
now redirection seems to work correctly, but if we try to make a link and take a look on generated html, the problem is still there...

['label' => 'English', 'url' => ['/','language'=>'en']]  ----> <a href="/en//">

**Comment by mikehaertl** [comment]
Ok, it's quite late here - I can't find a quick solution for this. Personally I never use `/` as a route, if I want to link to the home page. You could try to use the specific route instead, like `site/index`. This should work - at least that's what the test cases say.

**Comment by ebisbe** [comment]
Sorry I've had a nose operation on thursday and didn't check any email since then. I'll review your comments and check if it works fine for me as well

**Comment by mikehaertl** [comment]
@smilemd I'm not sure if i want to fix the `Url::to(['/'])` problem at all. This is very specific and there's a workaround (use `site/index` instead). If you still really think you need it, you can open a new issue for it. But don't expect a solution too soon.

Apart from that I think that most trailing slash issues are now resolved. I'll release 2.1.7 now with all the above fixes.

**Comment by mikehaertl** [comment]
@ebisbe Latest version 1.2.7 should just work. Ignore my comments about `trailingSlash` feature above. This feature was removed again.

**Comment by ebisbe** [comment]
@mikehaertl for me it's working. Thanks! I'll cancel my PR if not cancelled already.

**Comment by smilemd** [comment]
mikehaertl, please take a look on this PR.

https://github.com/codemix/yii2-localeurls/pull/46
