### ISSUE TITLE
Can not mix URLs with and w/o trailing slashes

### ISSUE THREAD

**Issue by Matvik** [codemix/yii2-localeurls#94]
From the SEO reasons there must be ending slashes in some URL rules. It works fine on the default language, but on the others ending slash disappears in generated URLs. But if the rule have dynamic part - all works fine. Example:
[
        'pattern' => '/products',
        'route' => '/catalog/default/index',
        'suffix' => '/',
    ],
not works.

[
        'pattern' => '/products/\<categorySlug\>',
        'route' => '/catalog/default/index',
        'suffix' => '/',
    ],
works fine.

**Comment by mikehaertl** [comment]
Hmm, I'll try to have a look. We already had several issues and I thought, we finally fixed everything related to trailing slashes.

Sidenote: I'm surprised how many people need those nasty trailing slashes. I've never used trailing slashes and remove them with a redirect in the webserver (Apache, Nginx) config. I've never had any issues with SEO or URL creation.

Could you maybe point to some official statements, why someone would ever want a trailing slash in their URLs?

**Comment by Matvik** [comment]
As my SEO-partner said, thees slashes are good in case, when the page is a "container" for the other pages. For example, catalog page in e-commerce solution is a container for goods pages, so it is good to show this in URL.

**Comment by mikehaertl** [comment]
Do you have any sources for this? I could not find this confirmed anywhere. The only issue where trailing slashes seem to matter is when it comes to duplicate content. SEO-experts say many things - to me it sometimes feels like a cult and we developers should not always follow ;). What really counts are reliable sources.

I still see what we can do. If I can reproduce the issue it's still something we have to fix to make everything work consistently.

**Comment by phpnode** [comment]
This SEO advice is superstition, no search engine is taking this into account at all because the real world web does not work like that. Source - I used to work in SEO, this wasn't true 10 years ago and isn't true now.

**Comment by SDKiller** [comment]
@phpnode 
I'm not great fan of SEO guys - as most of their advise look like shamancraft and voodoo.

But in real world you deal with a customer, who hires such a "SEO-guru". 
So if customer says "I pay SEO guys big money and they say that I need trailing slashes", developer has a choice - to provide trailing slashes or to search another customer. 
But he has no chance to argue with that SEO guys.

**Comment by Matvik** [comment]
From SEO part if we have "/" in the end of the URL it means that Search Robots has to find another internal out-links from this page and all value of the page will be shared with them. If we have no "/" in the end of the URL it means that it is the last page and all value has to be assigned only for this page.
On practice if we need optimize one page (don't share the search value) we have to put no "/" in the end of URL.

**Comment by mikehaertl** [comment]
@Matvik I can reproduce the issue. It basically always happens if the `suffix` in one of your URL rules does not match the `suffix` setting in the `urlManager`. In other words: If you try to mix trailing slash URLs with not trailing slash URLs in the same application.

There's no easy way to fix this. The library would become extremely bloated, if we supported this. It would probably also slow down URL processing as we'd have to re-run the URL creation logic a second time in our extension code, each time a URL is created.

So I'm sorry, but you should not expect any fix soon. Maybe you can still convince your SEO guy that things like this are not only not necessary but IMO bad practice.

**Comment by mikehaertl** [comment]
@Matvik I've found a way to solve the issue. Could you help testing? The fix is available on master.

**Comment by mikehaertl** [comment]
@Matvik Any news here?

**Comment by mikehaertl** [comment]
@Matvik We've release 1.4.8 containing the above fix. If you find time to test it, some feedback would be welcome.

Closing this for now as I think the issue should be fixed.

**Comment by Matvik** [comment]
Thanks! Sorry for a long waiting. I tested this fix. 
It works, but conflicts with **UrlNormalizer** - when UrlNormalizer is enabled and we has not default language, there is infinite redirecting.

**Comment by mikehaertl** [comment]
@Matvik Is this the same problem that you reported in #97? See the fix there.

**Comment by Matvik** [comment]
Sorry, that fix didn't fix this problem. I still have wrong redirection, using suffix on certain rule.
Here is urlManager config:
```
'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['uk' => 'uk-UA', 'ru' => 'ru-RU'],
            'enableDefaultLanguageUrlCode' => true,
            'enablePrettyUrl' => true,
            'baseUrl' => '/',
            'showScriptName' => false,
            'normalizer' => [
                'class' => 'yii\web\UrlNormalizer',
                'action' => yii\web\UrlNormalizer::ACTION_REDIRECT_PERMANENT,
            ],
            'rules' => require(__DIR__ . '/router.php')
        ],
```
and rule:
```
[
        'pattern' => '/blog/',
        'route' => '/blog/default/index',
        'suffix' => '/',
    ],
```
Firefox shows:

> The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

**Comment by mikehaertl** [comment]
@Matvik This should now also be fixed. Could you test the latest code on master please?

**Comment by Matvik** [comment]
It seems to work fine now. Many thanks! When this fix will be available by updating composer?

**Comment by mikehaertl** [comment]
I'm waiting for some feedback on the new issue #99. It's unclear yet, what this is about and if it's related to our latest changes. If we get green light there I'll create a new release.

**Comment by mikehaertl** [comment]
@Matvik Just released 1.4.10 which includes this fix. Thanks for your help.
